on:
  push:
    branches:
      - main
  workflow_dispatch:
  
jobs:
  run_pull:
    name: run pull
    runs-on: ubuntu-latest
    
    steps:
    - name: connect and pull
      run: ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} "uname -a && ls -l && date"
  
