on:
  push:
    branches:
      - main
  workflow_dispatch:
  
jobs:
  run_pull:
    name: run pull
    runs-on: ubuntu-latest


-name: Test
  env: 
    TEST_GITHUB_IP: ${{ secrets.SERVER_IP }}
    TEST_GITHUB_USER: ${{ secrets.SERVER_USER }}
    
  run: |
    echo ${#TEST_GITHUB_IP}
    ECHO ${#TEST_GITHUB_USER}
    
